version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "11:00"
    timezone: America/Chicago
  open-pull-requests-limit: 2
  target-branch: main
- package-ecosystem: github-actions
  target-branch: main
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "11:00"
    timezone: America/Chicago
