version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errname
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gomodguard
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
  settings:
    gosec:
      excludes:
        - G404
    lll:
      line-length: 130
    paralleltest:
      ignore-missing-subtests: true
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: pkg/tools/literaturetool/literature_tool_test.go
        linters:
          - funlen
        text: "Function 'TestNormalizeDOI' is too long"
      - path: pkg/tools/literaturetool/literature_tool_test.go
        linters:
          - funlen
        text: "Function 'TestHandler_ValidationErrors' is too long"
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
