name: Continuous integration
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v5
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
      - run: go version
      - name: unit test
        run: go test -covermode=atomic -coverprofile=coverage.txt ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV }}
