name: Lint
on:
  pull_request
jobs:
  lint:
    uses: dictyBase/workflows/.github/workflows/golang-lint.yaml@develop
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.sha }}
      version: v2.1.6-alpine
